### ISSUE TITLE
OFW support

### ISSUE THREAD

**Issue by krazynez** [catmagicspell/themadump#1]
Correct me if I am wrong but seems like your not signing your EBOOT at build time. Yoti has some tools to do that here: https://github.com/Yoti/psp_pspident/tree/master/psptools

Also I just made a theme dumper last night Yoti just let me know about this. ~~I can do a PR if you would like~~ to late I did 😁

**Comment by rreha** [comment]
Hello @krazynez, firstly we want to thank you for your interest! Unfortunately, we won't merge your PR, as we want to keep the Makefile as clean as possible. We prefer to do the signing and zipping process manually.

**Comment by krazynez** [comment]
> Hello @krazynez, firstly we want to thank you for your interest! Unfortunately, we won't merge your PR, as we want to keep the Makefile as clean as possible. We prefer to do the signing and zipping process manually.

No worries 👍
